* Changelog
** 0.2.28
Convenience macros for accessing slots (thanks to @lockie)
** 0.2.27
Add links to readme, Fixed and added definitions, Added missing package symbols
** 0.2.26
Fix and add missing color addon functions.  Added stream-file-position accesors for binary-stream
** 0.2.25
Add new keycodes.  Cleanup the interface a little and add joystick initialization
** 0.2.24
Fix for the interface running crossplatform.  Issue with the GUI code needing to run in the main thread on Darwin machines
** 0.2.23
Fix for audio system init and export initialize-system
** 0.2.22
Add missing export and remove nonexistent export related to ~Display~
** 0.2.21
Quick release, forgot to add missing package symbol exports
** 0.2.20
Adds new functionality from Allegro 5.2.9 and few other missing functions
** 0.2.19
Added Gray streams for filestreams (PR #36 by @lockie)

Added example for native message box

Fix bug with the (optional) interface with threading

** 0.2.18
Upgrading for the release of Allegro 5.2.8.  Along with adding new definitions, added older ones never added and exported symbols to package accidentally left out.

*** Graphics
~al_set_new_bitmap_depth~
~al_get_new_bitmap_depth~
~al_set_new_bitmap_samples~
~al_get_new_bitmap_samples~
~al_set_new_bitmap_wrap~
~al_get_new_bitmap_wrap~
~ALLEGRO_BITMAP_WRAP~

*** Shader
~ALLEGRO_SHADER_AUTO_MINIMAL~
~ALLEGRO_SHADER_GLSL_MINIMAL~
~ALLEGRO_SHADER_HLSL_MINIMAL~
~ALLEGRO_SHADER_HLSL_SM_3_0~

*** Audio addon
~ALLEGRO_AUDIO_RECORDER~
~ALLEGRO_AUDIO_RECORDER_EVENT~
~ALLEGRO_AUDIO_DEVICE~
~ALLEGRO_PLAYMODE_LOOP_ONCE~
~al_play_audio_stream~
~al_play_audio_stream_f~
~al_register_sample_identifier~
~al_identify_sample~
~al_identify_sample_f~
~al_lock_sample_id~
~al_unlock_sample_id~
~al_set_sample_instance_channel_matrix~
~al_set_audio_stream_channel_matrix~
~al_get_audio_stream_played_samples~
~al_create_audio_recorder~
~al_start_audio_recorder~
~al_stop_audio_recorder~
~al_is_audio_recorder_recording~
~al_get_audio_recorder_event~
~al_get_audio_recorder_event_source~
~al_destroy_audio_recorder~
~al_get_num_audio_output_devices~
~al_get_audio_output_device~
~al_get_audio_device_name~
~al_fill_silence~

*** Video addon
~al_identify_video~
~al_identify_video_f~

*** Color addon
~al_is_color_valid~
~al_color_rgb_to_oklab~
~al_color_oklab~
~al_color_oklab_to_rgb~
~al_color_rgb_to_linear~
~al_color_linear~
~al_color_linear_to_rgb~

** 0.2.17
- Add Allegro 5 Threads

** 0.2.16
- Add projects to readme using cl-liballegro
- Add changelog file to help devs keep track of changes
- Fix return value of ~init-font-addon~
- Add Allegro 5 Memory

** 0.2.15
- Add audio event type
- Fix incorrect function parameter for ~set-audio-stream-playing~

** 0.2.13
- Add Allegro 5 UTF-8
- Add additional documentation: https://resttime.github.io/cl-liballegro/
- Fix ~run-system~ on OSX

** 0.2.11
- Add Allegro 5 Video addon
- Add Allegro 5 Filesystem
- Fix compatibility for OSX requiring GUI code in main thread
- Fix variadic function definitions for ~al_draw_textf~ and ~al_draw_justified_textf~
