(in-package #:cl-allegro)

(define-foreign-library liballegro
  (:windows "allegro-5.0.8-monolith-mt.dll")
  (:unix (:default "liballegro")))
(define-foreign-library liballegro-acodec (:unix (:default "liballegro_acodec")))
(define-foreign-library liballegro-audio (:unix (:default "liballegro_audio")))
(define-foreign-library liballegro-color (:unix (:default "liballegro_color")))
(define-foreign-library liballegro-dialog (:unix (:default "liballegro_dialog")))
(define-foreign-library liballegro-font (:unix (:default "liballegro_font")))
(define-foreign-library liballegro-image (:unix (:default "liballegro_image")))
(define-foreign-library liballegro-memfile (:unix (:default "liballegro_memfile")))
(define-foreign-library liballegro-physfs (:unix (:default "liballegro_physfs")))
(define-foreign-library liballegro-primitives (:unix (:default "liballegro_primitives")))
(define-foreign-library liballegro-ttf (:unix (:default "liballegro_ttf")))

(use-foreign-library liballegro)
(use-foreign-library liballegro-acodec)
(use-foreign-library liballegro-audio)
(use-foreign-library liballegro-color)
(use-foreign-library liballegro-dialog)
(use-foreign-library liballegro-font)
(use-foreign-library liballegro-image)
(use-foreign-library liballegro-memfile)
(use-foreign-library liballegro-physfs)
(use-foreign-library liballegro-primitives)
(use-foreign-library liballegro-ttf)
