(in-package #:cl-liballegro)

(defun get-event-type (event)
  (foreign-slot-value event 'allegro-event 'type))
(defun get-any-event (event)
  (foreign-slot-value event 'allegro-event 'any))

(defun get-display-event (event)
  (foreign-slot-value event 'allegro-event 'display))
(defun get-display-event-type (event)
  (foreign-slot-value event 'allegro-display-event 'type))
(defun get-display-event-x (event)
  (foreign-slot-value event 'allegro-display-event 'x))
(defun get-display-event-y (event)
  (foreign-slot-value event 'allegro-display-event 'y))
(defun get-display-event-width (event)
  (foreign-slot-value event 'allegro-display-event 'width))
(defun get-display-event-height (event)
  (foreign-slot-value event 'allegro-display-event 'height))
(defun get-display-event-orientation (event)
  (foreign-slot-value event 'allegro-display-event 'orientation))
  
(defun get-joystick-event (event)
  (foreign-slot-value event 'allegro-event 'joystick))
(defun get-joystick-event-type (event)
  (foreign-slot-value event 'allegro-joystick-event 'type))
(defun get-joystick-event-id (event)
  (foreign-slot-value event 'allegro-joystick-event 'id))
(defun get-joystick-event-stick (event)
  (foreign-slot-value event 'allegro-joystick-event 'stick))
(defun get-joystick-event-axis (event)
  (foreign-slot-value event 'allegro-joystick-event 'axis))
(defun get-joystick-event-pos (event)
  (foreign-slot-value event 'allegro-joystick-event 'pos))
(defun get-joystick-event-button (event)
  (foreign-slot-value event 'allegro-joystick-event 'button))
 
(defun get-keyboard-event (event)
  (foreign-slot-value event 'allegro-event 'keyboard))
(defun get-keyboard-event-type (event)
  (foreign-slot-value event 'allegro-keyboard-event 'type))
(defun get-keyboard-event-display (event)
  (foreign-slot-value event 'allegro-keyboard-event 'display))
(defun get-keyboard-event-keycode (event)
  (foreign-slot-value event 'allegro-keyboard-event 'keycode))
(defun get-keyboard-event-unichar (event)
  (foreign-slot-value event 'allegro-keyboard-event 'unichar))
(defun get-keyboard-event-modifiers (event)
  (foreign-slot-value event 'allegro-keyboard-event 'modifiers))
(defun get-keyboard-event-repeat (event)
  (foreign-slot-value event 'allegro-keyboard-event 'repeat))  

(defun get-mouse-event (event)
  (foreign-slot-value event 'allegro-event 'mouse))
(defun get-mouse-event-type (event)
  (foreign-slot-value event 'allegro-mouse-event 'type))
(defun get-mouse-event-display (event)
  (foreign-slot-value event 'allegro-mouse-event 'display)) 
(defun get-mouse-event-x (event)
  (foreign-slot-value event 'allegro-mouse-event 'x))
(defun get-mouse-event-y (event)
  (foreign-slot-value event 'allegro-mouse-event 'y))
(defun get-mouse-event-z (event)
  (foreign-slot-value event 'allegro-mouse-event 'z))
(defun get-mouse-event-w (event)
  (foreign-slot-value event 'allegro-mouse-event 'w))
(defun get-mouse-event-dx (event)
  (foreign-slot-value event 'allegro-mouse-event 'dx))
(defun get-mouse-event-dy (event)
  (foreign-slot-value event 'allegro-mouse-event 'dy))
(defun get-mouse-event-dz (event)
  (foreign-slot-value event 'allegro-mouse-event 'dz))
(defun get-mouse-event-dw (event)
  (foreign-slot-value event 'allegro-mouse-event 'dw))
(defun get-mouse-event-button (event)
  (foreign-slot-value event 'allegro-mouse-event 'button))
(defun get-mouse-event-pressure (event)
  (foreign-slot-value event 'allegro-mouse-event 'pressure))  
  
(defun get-timer-event (event)
  (foreign-slot-value event 'allegro-event 'timer))
(defun get-timer-event-type (event)
  (foreign-slot-value event 'allegro-timer-event 'type))
(defun get-timer-event-count (event)
  (foreign-slot-value event 'allegro-timer-event 'count))  
  
(defun get-user-event (event)
  (foreign-slot-value event 'allegro-event 'timer))