(require "cl-liballegro")

(defvar *display*)
(defun main ()
  (al:init)
  (print "Create display")
  (setf *display* (al:create-display 800 600))
  (print "Clear BG")
  (al:clear-to-color 0.0 0.0 0.0 1.0)
  (print "Flip")
  (al:flip-display)
  (print "Rest")
  (al:rest-time 2.0d0)
  (print "done")
  (al:destroy-display *display*)
  (al:uninstall-system))
